// Generated by gencpp from file navigation_features/GetFeatureCountResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATION_FEATURES_MESSAGE_GETFEATURECOUNTRESPONSE_H
#define NAVIGATION_FEATURES_MESSAGE_GETFEATURECOUNTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation_features
{
template <class ContainerAllocator>
struct GetFeatureCountResponse_
{
  typedef GetFeatureCountResponse_<ContainerAllocator> Type;

  GetFeatureCountResponse_()
    : fc()  {
    }
  GetFeatureCountResponse_(const ContainerAllocator& _alloc)
    : fc(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _fc_type;
  _fc_type fc;





  typedef boost::shared_ptr< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFeatureCountResponse_

typedef ::navigation_features::GetFeatureCountResponse_<std::allocator<void> > GetFeatureCountResponse;

typedef boost::shared_ptr< ::navigation_features::GetFeatureCountResponse > GetFeatureCountResponsePtr;
typedef boost::shared_ptr< ::navigation_features::GetFeatureCountResponse const> GetFeatureCountResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_features

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'upo_msgs': ['/home/im_hongxian_yi/catkin_ws/src/upo_robot_navigation/upo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ef50b45be27f70251830b5acdacd737";
  }

  static const char* value(const ::navigation_features::GetFeatureCountResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ef50b45be27f702ULL;
  static const uint64_t static_value2 = 0x51830b5acdacd737ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_features/GetFeatureCountResponse";
  }

  static const char* value(const ::navigation_features::GetFeatureCountResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] fc\n\
\n\
";
  }

  static const char* value(const ::navigation_features::GetFeatureCountResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFeatureCountResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_features::GetFeatureCountResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_features::GetFeatureCountResponse_<ContainerAllocator>& v)
  {
    s << indent << "fc[]" << std::endl;
    for (size_t i = 0; i < v.fc.size(); ++i)
    {
      s << indent << "  fc[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.fc[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_FEATURES_MESSAGE_GETFEATURECOUNTRESPONSE_H
