// Generated by gencpp from file navigation_features/GetFeatureCount.msg
// DO NOT EDIT!


#ifndef NAVIGATION_FEATURES_MESSAGE_GETFEATURECOUNT_H
#define NAVIGATION_FEATURES_MESSAGE_GETFEATURECOUNT_H

#include <ros/service_traits.h>


#include <navigation_features/GetFeatureCountRequest.h>
#include <navigation_features/GetFeatureCountResponse.h>


namespace navigation_features
{

struct GetFeatureCount
{

typedef GetFeatureCountRequest Request;
typedef GetFeatureCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetFeatureCount
} // namespace navigation_features


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_features::GetFeatureCount > {
  static const char* value()
  {
    return "bcbe55a0b60ae0b44299673e70206f76";
  }

  static const char* value(const ::navigation_features::GetFeatureCount&) { return value(); }
};

template<>
struct DataType< ::navigation_features::GetFeatureCount > {
  static const char* value()
  {
    return "navigation_features/GetFeatureCount";
  }

  static const char* value(const ::navigation_features::GetFeatureCount&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_features::GetFeatureCountRequest> should match 
// service_traits::MD5Sum< ::navigation_features::GetFeatureCount > 
template<>
struct MD5Sum< ::navigation_features::GetFeatureCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_features::GetFeatureCount >::value();
  }
  static const char* value(const ::navigation_features::GetFeatureCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_features::GetFeatureCountRequest> should match 
// service_traits::DataType< ::navigation_features::GetFeatureCount > 
template<>
struct DataType< ::navigation_features::GetFeatureCountRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_features::GetFeatureCount >::value();
  }
  static const char* value(const ::navigation_features::GetFeatureCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_features::GetFeatureCountResponse> should match 
// service_traits::MD5Sum< ::navigation_features::GetFeatureCount > 
template<>
struct MD5Sum< ::navigation_features::GetFeatureCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_features::GetFeatureCount >::value();
  }
  static const char* value(const ::navigation_features::GetFeatureCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_features::GetFeatureCountResponse> should match 
// service_traits::DataType< ::navigation_features::GetFeatureCount > 
template<>
struct DataType< ::navigation_features::GetFeatureCountResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_features::GetFeatureCount >::value();
  }
  static const char* value(const ::navigation_features::GetFeatureCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_FEATURES_MESSAGE_GETFEATURECOUNT_H
