// Generated by gencpp from file navigation_features/InitWeightsRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_FEATURES_MESSAGE_INITWEIGHTSREQUEST_H
#define NAVIGATION_FEATURES_MESSAGE_INITWEIGHTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation_features
{
template <class ContainerAllocator>
struct InitWeightsRequest_
{
  typedef InitWeightsRequest_<ContainerAllocator> Type;

  InitWeightsRequest_()
    : random(false)
    , normalize(false)  {
    }
  InitWeightsRequest_(const ContainerAllocator& _alloc)
    : random(false)
    , normalize(false)  {
  (void)_alloc;
    }



   typedef uint8_t _random_type;
  _random_type random;

   typedef uint8_t _normalize_type;
  _normalize_type normalize;





  typedef boost::shared_ptr< ::navigation_features::InitWeightsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_features::InitWeightsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InitWeightsRequest_

typedef ::navigation_features::InitWeightsRequest_<std::allocator<void> > InitWeightsRequest;

typedef boost::shared_ptr< ::navigation_features::InitWeightsRequest > InitWeightsRequestPtr;
typedef boost::shared_ptr< ::navigation_features::InitWeightsRequest const> InitWeightsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_features::InitWeightsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_features::InitWeightsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_features

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'upo_msgs': ['/home/im_hongxian_yi/catkin_ws/src/upo_robot_navigation/upo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_features::InitWeightsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_features::InitWeightsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_features::InitWeightsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_features::InitWeightsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_features::InitWeightsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_features::InitWeightsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_features::InitWeightsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5d460e556a63181a097fbdfc6faca67";
  }

  static const char* value(const ::navigation_features::InitWeightsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5d460e556a63181ULL;
  static const uint64_t static_value2 = 0xa097fbdfc6faca67ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_features::InitWeightsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_features/InitWeightsRequest";
  }

  static const char* value(const ::navigation_features::InitWeightsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_features::InitWeightsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool random\n\
bool normalize\n\
";
  }

  static const char* value(const ::navigation_features::InitWeightsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_features::InitWeightsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.random);
      stream.next(m.normalize);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitWeightsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_features::InitWeightsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_features::InitWeightsRequest_<ContainerAllocator>& v)
  {
    s << indent << "random: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.random);
    s << indent << "normalize: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.normalize);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_FEATURES_MESSAGE_INITWEIGHTSREQUEST_H
