// Generated by gencpp from file navigation_features/InitWeights.msg
// DO NOT EDIT!


#ifndef NAVIGATION_FEATURES_MESSAGE_INITWEIGHTS_H
#define NAVIGATION_FEATURES_MESSAGE_INITWEIGHTS_H

#include <ros/service_traits.h>


#include <navigation_features/InitWeightsRequest.h>
#include <navigation_features/InitWeightsResponse.h>


namespace navigation_features
{

struct InitWeights
{

typedef InitWeightsRequest Request;
typedef InitWeightsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitWeights
} // namespace navigation_features


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_features::InitWeights > {
  static const char* value()
  {
    return "a974b2e5d8cf5299fc01afe16b877882";
  }

  static const char* value(const ::navigation_features::InitWeights&) { return value(); }
};

template<>
struct DataType< ::navigation_features::InitWeights > {
  static const char* value()
  {
    return "navigation_features/InitWeights";
  }

  static const char* value(const ::navigation_features::InitWeights&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_features::InitWeightsRequest> should match 
// service_traits::MD5Sum< ::navigation_features::InitWeights > 
template<>
struct MD5Sum< ::navigation_features::InitWeightsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_features::InitWeights >::value();
  }
  static const char* value(const ::navigation_features::InitWeightsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_features::InitWeightsRequest> should match 
// service_traits::DataType< ::navigation_features::InitWeights > 
template<>
struct DataType< ::navigation_features::InitWeightsRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_features::InitWeights >::value();
  }
  static const char* value(const ::navigation_features::InitWeightsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_features::InitWeightsResponse> should match 
// service_traits::MD5Sum< ::navigation_features::InitWeights > 
template<>
struct MD5Sum< ::navigation_features::InitWeightsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_features::InitWeights >::value();
  }
  static const char* value(const ::navigation_features::InitWeightsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_features::InitWeightsResponse> should match 
// service_traits::DataType< ::navigation_features::InitWeights > 
template<>
struct DataType< ::navigation_features::InitWeightsResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_features::InitWeights >::value();
  }
  static const char* value(const ::navigation_features::InitWeightsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_FEATURES_MESSAGE_INITWEIGHTS_H
