// Generated by gencpp from file navigation_features/PoseValidResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATION_FEATURES_MESSAGE_POSEVALIDRESPONSE_H
#define NAVIGATION_FEATURES_MESSAGE_POSEVALIDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation_features
{
template <class ContainerAllocator>
struct PoseValidResponse_
{
  typedef PoseValidResponse_<ContainerAllocator> Type;

  PoseValidResponse_()
    : ok(false)  {
    }
  PoseValidResponse_(const ContainerAllocator& _alloc)
    : ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::navigation_features::PoseValidResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_features::PoseValidResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PoseValidResponse_

typedef ::navigation_features::PoseValidResponse_<std::allocator<void> > PoseValidResponse;

typedef boost::shared_ptr< ::navigation_features::PoseValidResponse > PoseValidResponsePtr;
typedef boost::shared_ptr< ::navigation_features::PoseValidResponse const> PoseValidResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_features::PoseValidResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_features::PoseValidResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_features

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'upo_msgs': ['/home/im_hongxian_yi/catkin_ws/src/upo_robot_navigation/upo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_features::PoseValidResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_features::PoseValidResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_features::PoseValidResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_features::PoseValidResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_features::PoseValidResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_features::PoseValidResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_features::PoseValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const ::navigation_features::PoseValidResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_features::PoseValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_features/PoseValidResponse";
  }

  static const char* value(const ::navigation_features::PoseValidResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_features::PoseValidResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n\
\n\
";
  }

  static const char* value(const ::navigation_features::PoseValidResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_features::PoseValidResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PoseValidResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_features::PoseValidResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation_features::PoseValidResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_FEATURES_MESSAGE_POSEVALIDRESPONSE_H
