// Generated by gencpp from file navigation_features/SetLossCost.msg
// DO NOT EDIT!


#ifndef NAVIGATION_FEATURES_MESSAGE_SETLOSSCOST_H
#define NAVIGATION_FEATURES_MESSAGE_SETLOSSCOST_H

#include <ros/service_traits.h>


#include <navigation_features/SetLossCostRequest.h>
#include <navigation_features/SetLossCostResponse.h>


namespace navigation_features
{

struct SetLossCost
{

typedef SetLossCostRequest Request;
typedef SetLossCostResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLossCost
} // namespace navigation_features


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_features::SetLossCost > {
  static const char* value()
  {
    return "1ad92c7623984460307dafddcd731d68";
  }

  static const char* value(const ::navigation_features::SetLossCost&) { return value(); }
};

template<>
struct DataType< ::navigation_features::SetLossCost > {
  static const char* value()
  {
    return "navigation_features/SetLossCost";
  }

  static const char* value(const ::navigation_features::SetLossCost&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_features::SetLossCostRequest> should match 
// service_traits::MD5Sum< ::navigation_features::SetLossCost > 
template<>
struct MD5Sum< ::navigation_features::SetLossCostRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_features::SetLossCost >::value();
  }
  static const char* value(const ::navigation_features::SetLossCostRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_features::SetLossCostRequest> should match 
// service_traits::DataType< ::navigation_features::SetLossCost > 
template<>
struct DataType< ::navigation_features::SetLossCostRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_features::SetLossCost >::value();
  }
  static const char* value(const ::navigation_features::SetLossCostRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_features::SetLossCostResponse> should match 
// service_traits::MD5Sum< ::navigation_features::SetLossCost > 
template<>
struct MD5Sum< ::navigation_features::SetLossCostResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_features::SetLossCost >::value();
  }
  static const char* value(const ::navigation_features::SetLossCostResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_features::SetLossCostResponse> should match 
// service_traits::DataType< ::navigation_features::SetLossCost > 
template<>
struct DataType< ::navigation_features::SetLossCostResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_features::SetLossCost >::value();
  }
  static const char* value(const ::navigation_features::SetLossCostResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_FEATURES_MESSAGE_SETLOSSCOST_H
