// Generated by gencpp from file navigation_features/SetLossCostResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATION_FEATURES_MESSAGE_SETLOSSCOSTRESPONSE_H
#define NAVIGATION_FEATURES_MESSAGE_SETLOSSCOSTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation_features
{
template <class ContainerAllocator>
struct SetLossCostResponse_
{
  typedef SetLossCostResponse_<ContainerAllocator> Type;

  SetLossCostResponse_()
    {
    }
  SetLossCostResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::navigation_features::SetLossCostResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation_features::SetLossCostResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetLossCostResponse_

typedef ::navigation_features::SetLossCostResponse_<std::allocator<void> > SetLossCostResponse;

typedef boost::shared_ptr< ::navigation_features::SetLossCostResponse > SetLossCostResponsePtr;
typedef boost::shared_ptr< ::navigation_features::SetLossCostResponse const> SetLossCostResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation_features::SetLossCostResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation_features::SetLossCostResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation_features

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'upo_msgs': ['/home/im_hongxian_yi/catkin_ws/src/upo_robot_navigation/upo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation_features::SetLossCostResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation_features::SetLossCostResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_features::SetLossCostResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation_features::SetLossCostResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_features::SetLossCostResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation_features::SetLossCostResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation_features::SetLossCostResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::navigation_features::SetLossCostResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation_features::SetLossCostResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation_features/SetLossCostResponse";
  }

  static const char* value(const ::navigation_features::SetLossCostResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation_features::SetLossCostResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
";
  }

  static const char* value(const ::navigation_features::SetLossCostResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation_features::SetLossCostResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLossCostResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation_features::SetLossCostResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::navigation_features::SetLossCostResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_FEATURES_MESSAGE_SETLOSSCOSTRESPONSE_H
