// Generated by gencpp from file navigation_features/SetScenario.msg
// DO NOT EDIT!


#ifndef NAVIGATION_FEATURES_MESSAGE_SETSCENARIO_H
#define NAVIGATION_FEATURES_MESSAGE_SETSCENARIO_H

#include <ros/service_traits.h>


#include <navigation_features/SetScenarioRequest.h>
#include <navigation_features/SetScenarioResponse.h>


namespace navigation_features
{

struct SetScenario
{

typedef SetScenarioRequest Request;
typedef SetScenarioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetScenario
} // namespace navigation_features


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation_features::SetScenario > {
  static const char* value()
  {
    return "d1a8c49e0969fcedfee28e334b2ff779";
  }

  static const char* value(const ::navigation_features::SetScenario&) { return value(); }
};

template<>
struct DataType< ::navigation_features::SetScenario > {
  static const char* value()
  {
    return "navigation_features/SetScenario";
  }

  static const char* value(const ::navigation_features::SetScenario&) { return value(); }
};


// service_traits::MD5Sum< ::navigation_features::SetScenarioRequest> should match 
// service_traits::MD5Sum< ::navigation_features::SetScenario > 
template<>
struct MD5Sum< ::navigation_features::SetScenarioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_features::SetScenario >::value();
  }
  static const char* value(const ::navigation_features::SetScenarioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_features::SetScenarioRequest> should match 
// service_traits::DataType< ::navigation_features::SetScenario > 
template<>
struct DataType< ::navigation_features::SetScenarioRequest>
{
  static const char* value()
  {
    return DataType< ::navigation_features::SetScenario >::value();
  }
  static const char* value(const ::navigation_features::SetScenarioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation_features::SetScenarioResponse> should match 
// service_traits::MD5Sum< ::navigation_features::SetScenario > 
template<>
struct MD5Sum< ::navigation_features::SetScenarioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation_features::SetScenario >::value();
  }
  static const char* value(const ::navigation_features::SetScenarioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation_features::SetScenarioResponse> should match 
// service_traits::DataType< ::navigation_features::SetScenario > 
template<>
struct DataType< ::navigation_features::SetScenarioResponse>
{
  static const char* value()
  {
    return DataType< ::navigation_features::SetScenario >::value();
  }
  static const char* value(const ::navigation_features::SetScenarioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_FEATURES_MESSAGE_SETSCENARIO_H
