// Generated by gencpp from file upo_social_layer/Features.msg
// DO NOT EDIT!


#ifndef UPO_SOCIAL_LAYER_MESSAGE_FEATURES_H
#define UPO_SOCIAL_LAYER_MESSAGE_FEATURES_H

#include <ros/service_traits.h>


#include <upo_social_layer/FeaturesRequest.h>
#include <upo_social_layer/FeaturesResponse.h>


namespace upo_social_layer
{

struct Features
{

typedef FeaturesRequest Request;
typedef FeaturesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Features
} // namespace upo_social_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::upo_social_layer::Features > {
  static const char* value()
  {
    return "d0f680e5a790f292b7ddcbc7f490dfa6";
  }

  static const char* value(const ::upo_social_layer::Features&) { return value(); }
};

template<>
struct DataType< ::upo_social_layer::Features > {
  static const char* value()
  {
    return "upo_social_layer/Features";
  }

  static const char* value(const ::upo_social_layer::Features&) { return value(); }
};


// service_traits::MD5Sum< ::upo_social_layer::FeaturesRequest> should match 
// service_traits::MD5Sum< ::upo_social_layer::Features > 
template<>
struct MD5Sum< ::upo_social_layer::FeaturesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::upo_social_layer::Features >::value();
  }
  static const char* value(const ::upo_social_layer::FeaturesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_social_layer::FeaturesRequest> should match 
// service_traits::DataType< ::upo_social_layer::Features > 
template<>
struct DataType< ::upo_social_layer::FeaturesRequest>
{
  static const char* value()
  {
    return DataType< ::upo_social_layer::Features >::value();
  }
  static const char* value(const ::upo_social_layer::FeaturesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::upo_social_layer::FeaturesResponse> should match 
// service_traits::MD5Sum< ::upo_social_layer::Features > 
template<>
struct MD5Sum< ::upo_social_layer::FeaturesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::upo_social_layer::Features >::value();
  }
  static const char* value(const ::upo_social_layer::FeaturesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_social_layer::FeaturesResponse> should match 
// service_traits::DataType< ::upo_social_layer::Features > 
template<>
struct DataType< ::upo_social_layer::FeaturesResponse>
{
  static const char* value()
  {
    return DataType< ::upo_social_layer::Features >::value();
  }
  static const char* value(const ::upo_social_layer::FeaturesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UPO_SOCIAL_LAYER_MESSAGE_FEATURES_H
