// Generated by gencpp from file upo_social_layer/SetDemoPathRequest.msg
// DO NOT EDIT!


#ifndef UPO_SOCIAL_LAYER_MESSAGE_SETDEMOPATHREQUEST_H
#define UPO_SOCIAL_LAYER_MESSAGE_SETDEMOPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace upo_social_layer
{
template <class ContainerAllocator>
struct SetDemoPathRequest_
{
  typedef SetDemoPathRequest_<ContainerAllocator> Type;

  SetDemoPathRequest_()
    : demo()
    , use_loss_func(false)  {
    }
  SetDemoPathRequest_(const ContainerAllocator& _alloc)
    : demo(_alloc)
    , use_loss_func(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PoseStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::other >  _demo_type;
  _demo_type demo;

   typedef uint8_t _use_loss_func_type;
  _use_loss_func_type use_loss_func;





  typedef boost::shared_ptr< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDemoPathRequest_

typedef ::upo_social_layer::SetDemoPathRequest_<std::allocator<void> > SetDemoPathRequest;

typedef boost::shared_ptr< ::upo_social_layer::SetDemoPathRequest > SetDemoPathRequestPtr;
typedef boost::shared_ptr< ::upo_social_layer::SetDemoPathRequest const> SetDemoPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace upo_social_layer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c59916b1047dd2d21fe199789f24e2a1";
  }

  static const char* value(const ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc59916b1047dd2d2ULL;
  static const uint64_t static_value2 = 0x1fe199789f24e2a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upo_social_layer/SetDemoPathRequest";
  }

  static const char* value(const ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped[] demo\n\
bool use_loss_func\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.demo);
      stream.next(m.use_loss_func);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDemoPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upo_social_layer::SetDemoPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "demo[]" << std::endl;
    for (size_t i = 0; i < v.demo.size(); ++i)
    {
      s << indent << "  demo[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.demo[i]);
    }
    s << indent << "use_loss_func: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.use_loss_func);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPO_SOCIAL_LAYER_MESSAGE_SETDEMOPATHREQUEST_H
