// Generated by gencpp from file upo_social_layer/SetGoal.msg
// DO NOT EDIT!


#ifndef UPO_SOCIAL_LAYER_MESSAGE_SETGOAL_H
#define UPO_SOCIAL_LAYER_MESSAGE_SETGOAL_H

#include <ros/service_traits.h>


#include <upo_social_layer/SetGoalRequest.h>
#include <upo_social_layer/SetGoalResponse.h>


namespace upo_social_layer
{

struct SetGoal
{

typedef SetGoalRequest Request;
typedef SetGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGoal
} // namespace upo_social_layer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::upo_social_layer::SetGoal > {
  static const char* value()
  {
    return "85ae384b155cfbcdf597bf321f1d0169";
  }

  static const char* value(const ::upo_social_layer::SetGoal&) { return value(); }
};

template<>
struct DataType< ::upo_social_layer::SetGoal > {
  static const char* value()
  {
    return "upo_social_layer/SetGoal";
  }

  static const char* value(const ::upo_social_layer::SetGoal&) { return value(); }
};


// service_traits::MD5Sum< ::upo_social_layer::SetGoalRequest> should match 
// service_traits::MD5Sum< ::upo_social_layer::SetGoal > 
template<>
struct MD5Sum< ::upo_social_layer::SetGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::upo_social_layer::SetGoal >::value();
  }
  static const char* value(const ::upo_social_layer::SetGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_social_layer::SetGoalRequest> should match 
// service_traits::DataType< ::upo_social_layer::SetGoal > 
template<>
struct DataType< ::upo_social_layer::SetGoalRequest>
{
  static const char* value()
  {
    return DataType< ::upo_social_layer::SetGoal >::value();
  }
  static const char* value(const ::upo_social_layer::SetGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::upo_social_layer::SetGoalResponse> should match 
// service_traits::MD5Sum< ::upo_social_layer::SetGoal > 
template<>
struct MD5Sum< ::upo_social_layer::SetGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::upo_social_layer::SetGoal >::value();
  }
  static const char* value(const ::upo_social_layer::SetGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_social_layer::SetGoalResponse> should match 
// service_traits::DataType< ::upo_social_layer::SetGoal > 
template<>
struct DataType< ::upo_social_layer::SetGoalResponse>
{
  static const char* value()
  {
    return DataType< ::upo_social_layer::SetGoal >::value();
  }
  static const char* value(const ::upo_social_layer::SetGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UPO_SOCIAL_LAYER_MESSAGE_SETGOAL_H
