// Generated by gencpp from file gmm_sampling/GetApproachGMMProbsRequest.msg
// DO NOT EDIT!


#ifndef GMM_SAMPLING_MESSAGE_GETAPPROACHGMMPROBSREQUEST_H
#define GMM_SAMPLING_MESSAGE_GETAPPROACHGMMPROBSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gmm_sampling
{
template <class ContainerAllocator>
struct GetApproachGMMProbsRequest_
{
  typedef GetApproachGMMProbsRequest_<ContainerAllocator> Type;

  GetApproachGMMProbsRequest_()
    : x()
    , y()
    , person_orientation(0.0)  {
    }
  GetApproachGMMProbsRequest_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , person_orientation(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _x_type;
  _x_type x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _y_type;
  _y_type y;

   typedef float _person_orientation_type;
  _person_orientation_type person_orientation;





  typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetApproachGMMProbsRequest_

typedef ::gmm_sampling::GetApproachGMMProbsRequest_<std::allocator<void> > GetApproachGMMProbsRequest;

typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbsRequest > GetApproachGMMProbsRequestPtr;
typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbsRequest const> GetApproachGMMProbsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gmm_sampling

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4d06fe277e8bb25217c725744e05c2f";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4d06fe277e8bb25ULL;
  static const uint64_t static_value2 = 0x217c725744e05c2fULL;
};

template<class ContainerAllocator>
struct DataType< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gmm_sampling/GetApproachGMMProbsRequest";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] x\n\
float32[] y\n\
float32 person_orientation\n\
";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.person_orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetApproachGMMProbsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gmm_sampling::GetApproachGMMProbsRequest_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "person_orientation: ";
    Printer<float>::stream(s, indent + "  ", v.person_orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GMM_SAMPLING_MESSAGE_GETAPPROACHGMMPROBSREQUEST_H
