// Generated by gencpp from file gmm_sampling/GetApproachGMMSamplesResponse.msg
// DO NOT EDIT!


#ifndef GMM_SAMPLING_MESSAGE_GETAPPROACHGMMSAMPLESRESPONSE_H
#define GMM_SAMPLING_MESSAGE_GETAPPROACHGMMSAMPLESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gmm_sampling
{
template <class ContainerAllocator>
struct GetApproachGMMSamplesResponse_
{
  typedef GetApproachGMMSamplesResponse_<ContainerAllocator> Type;

  GetApproachGMMSamplesResponse_()
    : distances()
    , orientations()  {
    }
  GetApproachGMMSamplesResponse_(const ContainerAllocator& _alloc)
    : distances(_alloc)
    , orientations(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _distances_type;
  _distances_type distances;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _orientations_type;
  _orientations_type orientations;





  typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetApproachGMMSamplesResponse_

typedef ::gmm_sampling::GetApproachGMMSamplesResponse_<std::allocator<void> > GetApproachGMMSamplesResponse;

typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMSamplesResponse > GetApproachGMMSamplesResponsePtr;
typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMSamplesResponse const> GetApproachGMMSamplesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gmm_sampling

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63f275c709dd0fea8682d4dab777a67a";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63f275c709dd0feaULL;
  static const uint64_t static_value2 = 0x8682d4dab777a67aULL;
};

template<class ContainerAllocator>
struct DataType< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gmm_sampling/GetApproachGMMSamplesResponse";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] distances\n\
float32[] orientations\n\
\n\
";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distances);
      stream.next(m.orientations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetApproachGMMSamplesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gmm_sampling::GetApproachGMMSamplesResponse_<ContainerAllocator>& v)
  {
    s << indent << "distances[]" << std::endl;
    for (size_t i = 0; i < v.distances.size(); ++i)
    {
      s << indent << "  distances[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.distances[i]);
    }
    s << indent << "orientations[]" << std::endl;
    for (size_t i = 0; i < v.orientations.size(); ++i)
    {
      s << indent << "  orientations[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.orientations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GMM_SAMPLING_MESSAGE_GETAPPROACHGMMSAMPLESRESPONSE_H
