// Generated by gencpp from file gmm_sampling/GetApproachGMMProbsResponse.msg
// DO NOT EDIT!


#ifndef GMM_SAMPLING_MESSAGE_GETAPPROACHGMMPROBSRESPONSE_H
#define GMM_SAMPLING_MESSAGE_GETAPPROACHGMMPROBSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gmm_sampling
{
template <class ContainerAllocator>
struct GetApproachGMMProbsResponse_
{
  typedef GetApproachGMMProbsResponse_<ContainerAllocator> Type;

  GetApproachGMMProbsResponse_()
    : probs()  {
    }
  GetApproachGMMProbsResponse_(const ContainerAllocator& _alloc)
    : probs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _probs_type;
  _probs_type probs;





  typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetApproachGMMProbsResponse_

typedef ::gmm_sampling::GetApproachGMMProbsResponse_<std::allocator<void> > GetApproachGMMProbsResponse;

typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbsResponse > GetApproachGMMProbsResponsePtr;
typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbsResponse const> GetApproachGMMProbsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gmm_sampling

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47d9867c355f21d454eb271e7f61b3c8";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47d9867c355f21d4ULL;
  static const uint64_t static_value2 = 0x54eb271e7f61b3c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gmm_sampling/GetApproachGMMProbsResponse";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] probs\n\
\n\
";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.probs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetApproachGMMProbsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gmm_sampling::GetApproachGMMProbsResponse_<ContainerAllocator>& v)
  {
    s << indent << "probs[]" << std::endl;
    for (size_t i = 0; i < v.probs.size(); ++i)
    {
      s << indent << "  probs[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.probs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GMM_SAMPLING_MESSAGE_GETAPPROACHGMMPROBSRESPONSE_H
