// Generated by gencpp from file gmm_sampling/GetApproachGMMSamplesRequest.msg
// DO NOT EDIT!


#ifndef GMM_SAMPLING_MESSAGE_GETAPPROACHGMMSAMPLESREQUEST_H
#define GMM_SAMPLING_MESSAGE_GETAPPROACHGMMSAMPLESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gmm_sampling
{
template <class ContainerAllocator>
struct GetApproachGMMSamplesRequest_
{
  typedef GetApproachGMMSamplesRequest_<ContainerAllocator> Type;

  GetApproachGMMSamplesRequest_()
    : person_orientation(0.0)
    , num_samples(0)  {
    }
  GetApproachGMMSamplesRequest_(const ContainerAllocator& _alloc)
    : person_orientation(0.0)
    , num_samples(0)  {
  (void)_alloc;
    }



   typedef float _person_orientation_type;
  _person_orientation_type person_orientation;

   typedef int32_t _num_samples_type;
  _num_samples_type num_samples;





  typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetApproachGMMSamplesRequest_

typedef ::gmm_sampling::GetApproachGMMSamplesRequest_<std::allocator<void> > GetApproachGMMSamplesRequest;

typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMSamplesRequest > GetApproachGMMSamplesRequestPtr;
typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMSamplesRequest const> GetApproachGMMSamplesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gmm_sampling

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ccac130b5a98169f8b1a55b56a21b0c";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ccac130b5a98169ULL;
  static const uint64_t static_value2 = 0xf8b1a55b56a21b0cULL;
};

template<class ContainerAllocator>
struct DataType< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gmm_sampling/GetApproachGMMSamplesRequest";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 person_orientation\n\
int32 num_samples\n\
";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.person_orientation);
      stream.next(m.num_samples);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetApproachGMMSamplesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gmm_sampling::GetApproachGMMSamplesRequest_<ContainerAllocator>& v)
  {
    s << indent << "person_orientation: ";
    Printer<float>::stream(s, indent + "  ", v.person_orientation);
    s << indent << "num_samples: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_samples);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GMM_SAMPLING_MESSAGE_GETAPPROACHGMMSAMPLESREQUEST_H
