// Generated by gencpp from file gmm_sampling/GetApproachGMMProbRequest.msg
// DO NOT EDIT!


#ifndef GMM_SAMPLING_MESSAGE_GETAPPROACHGMMPROBREQUEST_H
#define GMM_SAMPLING_MESSAGE_GETAPPROACHGMMPROBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gmm_sampling
{
template <class ContainerAllocator>
struct GetApproachGMMProbRequest_
{
  typedef GetApproachGMMProbRequest_<ContainerAllocator> Type;

  GetApproachGMMProbRequest_()
    : x(0.0)
    , y(0.0)
    , person_orientation(0.0)  {
    }
  GetApproachGMMProbRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , person_orientation(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _person_orientation_type;
  _person_orientation_type person_orientation;





  typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetApproachGMMProbRequest_

typedef ::gmm_sampling::GetApproachGMMProbRequest_<std::allocator<void> > GetApproachGMMProbRequest;

typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbRequest > GetApproachGMMProbRequestPtr;
typedef boost::shared_ptr< ::gmm_sampling::GetApproachGMMProbRequest const> GetApproachGMMProbRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gmm_sampling

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16847feb0a2ef5fe7336b5b01ad1ab84";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16847feb0a2ef5feULL;
  static const uint64_t static_value2 = 0x7336b5b01ad1ab84ULL;
};

template<class ContainerAllocator>
struct DataType< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gmm_sampling/GetApproachGMMProbRequest";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 person_orientation\n\
";
  }

  static const char* value(const ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.person_orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetApproachGMMProbRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gmm_sampling::GetApproachGMMProbRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "person_orientation: ";
    Printer<float>::stream(s, indent + "  ", v.person_orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GMM_SAMPLING_MESSAGE_GETAPPROACHGMMPROBREQUEST_H
