(cl:defpackage upo_social_layer-srv
  (:use )
  (:export
   "COST"
   "<COST-REQUEST>"
   "COST-REQUEST"
   "<COST-RESPONSE>"
   "COST-RESPONSE"
   "FEATURES"
   "<FEATURES-REQUEST>"
   "FEATURES-REQUEST"
   "<FEATURES-RESPONSE>"
   "FEATURES-RESPONSE"
   "SETDEMOPATH"
   "<SETDEMOPATH-REQUEST>"
   "SETDEMOPATH-REQUEST"
   "<SETDEMOPATH-RESPONSE>"
   "SETDEMOPATH-RESPONSE"
   "SETGOAL"
   "<SETGOAL-REQUEST>"
   "SETGOAL-REQUEST"
   "<SETGOAL-RESPONSE>"
   "SETGOAL-RESPONSE"
  ))

