(cl:defpackage upo_navigation-srv
  (:use )
  (:export
   "FEATURECOUNTS"
   "<FEATURECOUNTS-REQUEST>"
   "FEATURECOUNTS-REQUEST"
   "<FEATURECOUNTS-RESPONSE>"
   "FEATURECOUNTS-RESPONSE"
   "POINTCOSTS"
   "<POINTCOSTS-REQUEST>"
   "POINTCOSTS-REQUEST"
   "<POINTCOSTS-RESPONSE>"
   "POINTCOSTS-RESPONSE"
   "SETWEIGHTS"
   "<SETWEIGHTS-REQUEST>"
   "SETWEIGHTS-REQUEST"
   "<SETWEIGHTS-RESPONSE>"
   "SETWEIGHTS-RESPONSE"
  ))

