// Generated by gencpp from file upo_navigation/FeatureCountsResponse.msg
// DO NOT EDIT!


#ifndef UPO_NAVIGATION_MESSAGE_FEATURECOUNTSRESPONSE_H
#define UPO_NAVIGATION_MESSAGE_FEATURECOUNTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upo_navigation
{
template <class ContainerAllocator>
struct FeatureCountsResponse_
{
  typedef FeatureCountsResponse_<ContainerAllocator> Type;

  FeatureCountsResponse_()
    : features()  {
    }
  FeatureCountsResponse_(const ContainerAllocator& _alloc)
    : features(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _features_type;
  _features_type features;





  typedef boost::shared_ptr< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct FeatureCountsResponse_

typedef ::upo_navigation::FeatureCountsResponse_<std::allocator<void> > FeatureCountsResponse;

typedef boost::shared_ptr< ::upo_navigation::FeatureCountsResponse > FeatureCountsResponsePtr;
typedef boost::shared_ptr< ::upo_navigation::FeatureCountsResponse const> FeatureCountsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace upo_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'upo_msgs': ['/home/im_hongxian_yi/catkin_ws/src/upo_robot_navigation/upo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1eff39aaa9756f3221a187400752fb2e";
  }

  static const char* value(const ::upo_navigation::FeatureCountsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1eff39aaa9756f32ULL;
  static const uint64_t static_value2 = 0x21a187400752fb2eULL;
};

template<class ContainerAllocator>
struct DataType< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upo_navigation/FeatureCountsResponse";
  }

  static const char* value(const ::upo_navigation::FeatureCountsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] features\n\
\n\
";
  }

  static const char* value(const ::upo_navigation::FeatureCountsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.features);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FeatureCountsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upo_navigation::FeatureCountsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upo_navigation::FeatureCountsResponse_<ContainerAllocator>& v)
  {
    s << indent << "features[]" << std::endl;
    for (size_t i = 0; i < v.features.size(); ++i)
    {
      s << indent << "  features[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.features[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPO_NAVIGATION_MESSAGE_FEATURECOUNTSRESPONSE_H
