// Generated by gencpp from file upo_navigation/FeatureCounts.msg
// DO NOT EDIT!


#ifndef UPO_NAVIGATION_MESSAGE_FEATURECOUNTS_H
#define UPO_NAVIGATION_MESSAGE_FEATURECOUNTS_H

#include <ros/service_traits.h>


#include <upo_navigation/FeatureCountsRequest.h>
#include <upo_navigation/FeatureCountsResponse.h>


namespace upo_navigation
{

struct FeatureCounts
{

typedef FeatureCountsRequest Request;
typedef FeatureCountsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FeatureCounts
} // namespace upo_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::upo_navigation::FeatureCounts > {
  static const char* value()
  {
    return "083cfa3c4c78c3b6c6861b11abdcb99a";
  }

  static const char* value(const ::upo_navigation::FeatureCounts&) { return value(); }
};

template<>
struct DataType< ::upo_navigation::FeatureCounts > {
  static const char* value()
  {
    return "upo_navigation/FeatureCounts";
  }

  static const char* value(const ::upo_navigation::FeatureCounts&) { return value(); }
};


// service_traits::MD5Sum< ::upo_navigation::FeatureCountsRequest> should match 
// service_traits::MD5Sum< ::upo_navigation::FeatureCounts > 
template<>
struct MD5Sum< ::upo_navigation::FeatureCountsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::upo_navigation::FeatureCounts >::value();
  }
  static const char* value(const ::upo_navigation::FeatureCountsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_navigation::FeatureCountsRequest> should match 
// service_traits::DataType< ::upo_navigation::FeatureCounts > 
template<>
struct DataType< ::upo_navigation::FeatureCountsRequest>
{
  static const char* value()
  {
    return DataType< ::upo_navigation::FeatureCounts >::value();
  }
  static const char* value(const ::upo_navigation::FeatureCountsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::upo_navigation::FeatureCountsResponse> should match 
// service_traits::MD5Sum< ::upo_navigation::FeatureCounts > 
template<>
struct MD5Sum< ::upo_navigation::FeatureCountsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::upo_navigation::FeatureCounts >::value();
  }
  static const char* value(const ::upo_navigation::FeatureCountsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_navigation::FeatureCountsResponse> should match 
// service_traits::DataType< ::upo_navigation::FeatureCounts > 
template<>
struct DataType< ::upo_navigation::FeatureCountsResponse>
{
  static const char* value()
  {
    return DataType< ::upo_navigation::FeatureCounts >::value();
  }
  static const char* value(const ::upo_navigation::FeatureCountsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UPO_NAVIGATION_MESSAGE_FEATURECOUNTS_H
