// Generated by gencpp from file upo_navigation/SetWeightsResponse.msg
// DO NOT EDIT!


#ifndef UPO_NAVIGATION_MESSAGE_SETWEIGHTSRESPONSE_H
#define UPO_NAVIGATION_MESSAGE_SETWEIGHTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upo_navigation
{
template <class ContainerAllocator>
struct SetWeightsResponse_
{
  typedef SetWeightsResponse_<ContainerAllocator> Type;

  SetWeightsResponse_()
    {
    }
  SetWeightsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetWeightsResponse_

typedef ::upo_navigation::SetWeightsResponse_<std::allocator<void> > SetWeightsResponse;

typedef boost::shared_ptr< ::upo_navigation::SetWeightsResponse > SetWeightsResponsePtr;
typedef boost::shared_ptr< ::upo_navigation::SetWeightsResponse const> SetWeightsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upo_navigation::SetWeightsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace upo_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'upo_msgs': ['/home/im_hongxian_yi/catkin_ws/src/upo_robot_navigation/upo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::upo_navigation::SetWeightsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upo_navigation/SetWeightsResponse";
  }

  static const char* value(const ::upo_navigation::SetWeightsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
";
  }

  static const char* value(const ::upo_navigation::SetWeightsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetWeightsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upo_navigation::SetWeightsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::upo_navigation::SetWeightsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UPO_NAVIGATION_MESSAGE_SETWEIGHTSRESPONSE_H
