// Generated by gencpp from file upo_navigation/SetWeights.msg
// DO NOT EDIT!


#ifndef UPO_NAVIGATION_MESSAGE_SETWEIGHTS_H
#define UPO_NAVIGATION_MESSAGE_SETWEIGHTS_H

#include <ros/service_traits.h>


#include <upo_navigation/SetWeightsRequest.h>
#include <upo_navigation/SetWeightsResponse.h>


namespace upo_navigation
{

struct SetWeights
{

typedef SetWeightsRequest Request;
typedef SetWeightsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetWeights
} // namespace upo_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::upo_navigation::SetWeights > {
  static const char* value()
  {
    return "d5ad370da8a2ea46419264bcdd331bf8";
  }

  static const char* value(const ::upo_navigation::SetWeights&) { return value(); }
};

template<>
struct DataType< ::upo_navigation::SetWeights > {
  static const char* value()
  {
    return "upo_navigation/SetWeights";
  }

  static const char* value(const ::upo_navigation::SetWeights&) { return value(); }
};


// service_traits::MD5Sum< ::upo_navigation::SetWeightsRequest> should match 
// service_traits::MD5Sum< ::upo_navigation::SetWeights > 
template<>
struct MD5Sum< ::upo_navigation::SetWeightsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::upo_navigation::SetWeights >::value();
  }
  static const char* value(const ::upo_navigation::SetWeightsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_navigation::SetWeightsRequest> should match 
// service_traits::DataType< ::upo_navigation::SetWeights > 
template<>
struct DataType< ::upo_navigation::SetWeightsRequest>
{
  static const char* value()
  {
    return DataType< ::upo_navigation::SetWeights >::value();
  }
  static const char* value(const ::upo_navigation::SetWeightsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::upo_navigation::SetWeightsResponse> should match 
// service_traits::MD5Sum< ::upo_navigation::SetWeights > 
template<>
struct MD5Sum< ::upo_navigation::SetWeightsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::upo_navigation::SetWeights >::value();
  }
  static const char* value(const ::upo_navigation::SetWeightsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_navigation::SetWeightsResponse> should match 
// service_traits::DataType< ::upo_navigation::SetWeights > 
template<>
struct DataType< ::upo_navigation::SetWeightsResponse>
{
  static const char* value()
  {
    return DataType< ::upo_navigation::SetWeights >::value();
  }
  static const char* value(const ::upo_navigation::SetWeightsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UPO_NAVIGATION_MESSAGE_SETWEIGHTS_H
