// Generated by gencpp from file upo_rrt_planners/MakePlan.msg
// DO NOT EDIT!


#ifndef UPO_RRT_PLANNERS_MESSAGE_MAKEPLAN_H
#define UPO_RRT_PLANNERS_MESSAGE_MAKEPLAN_H

#include <ros/service_traits.h>


#include <upo_rrt_planners/MakePlanRequest.h>
#include <upo_rrt_planners/MakePlanResponse.h>


namespace upo_rrt_planners
{

struct MakePlan
{

typedef MakePlanRequest Request;
typedef MakePlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MakePlan
} // namespace upo_rrt_planners


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::upo_rrt_planners::MakePlan > {
  static const char* value()
  {
    return "85c3c89353aa120e7e9dae5288c9f0f0";
  }

  static const char* value(const ::upo_rrt_planners::MakePlan&) { return value(); }
};

template<>
struct DataType< ::upo_rrt_planners::MakePlan > {
  static const char* value()
  {
    return "upo_rrt_planners/MakePlan";
  }

  static const char* value(const ::upo_rrt_planners::MakePlan&) { return value(); }
};


// service_traits::MD5Sum< ::upo_rrt_planners::MakePlanRequest> should match 
// service_traits::MD5Sum< ::upo_rrt_planners::MakePlan > 
template<>
struct MD5Sum< ::upo_rrt_planners::MakePlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::upo_rrt_planners::MakePlan >::value();
  }
  static const char* value(const ::upo_rrt_planners::MakePlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_rrt_planners::MakePlanRequest> should match 
// service_traits::DataType< ::upo_rrt_planners::MakePlan > 
template<>
struct DataType< ::upo_rrt_planners::MakePlanRequest>
{
  static const char* value()
  {
    return DataType< ::upo_rrt_planners::MakePlan >::value();
  }
  static const char* value(const ::upo_rrt_planners::MakePlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::upo_rrt_planners::MakePlanResponse> should match 
// service_traits::MD5Sum< ::upo_rrt_planners::MakePlan > 
template<>
struct MD5Sum< ::upo_rrt_planners::MakePlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::upo_rrt_planners::MakePlan >::value();
  }
  static const char* value(const ::upo_rrt_planners::MakePlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_rrt_planners::MakePlanResponse> should match 
// service_traits::DataType< ::upo_rrt_planners::MakePlan > 
template<>
struct DataType< ::upo_rrt_planners::MakePlanResponse>
{
  static const char* value()
  {
    return DataType< ::upo_rrt_planners::MakePlan >::value();
  }
  static const char* value(const ::upo_rrt_planners::MakePlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UPO_RRT_PLANNERS_MESSAGE_MAKEPLAN_H
