// Generated by gencpp from file upo_rrt_planners/MakePlanCostmapRequest.msg
// DO NOT EDIT!


#ifndef UPO_RRT_PLANNERS_MESSAGE_MAKEPLANCOSTMAPREQUEST_H
#define UPO_RRT_PLANNERS_MESSAGE_MAKEPLANCOSTMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <nav_msgs/OccupancyGrid.h>

namespace upo_rrt_planners
{
template <class ContainerAllocator>
struct MakePlanCostmapRequest_
{
  typedef MakePlanCostmapRequest_<ContainerAllocator> Type;

  MakePlanCostmapRequest_()
    : goal()
    , costmap()  {
    }
  MakePlanCostmapRequest_(const ContainerAllocator& _alloc)
    : goal(_alloc)
    , costmap(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef  ::nav_msgs::OccupancyGrid_<ContainerAllocator>  _costmap_type;
  _costmap_type costmap;





  typedef boost::shared_ptr< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MakePlanCostmapRequest_

typedef ::upo_rrt_planners::MakePlanCostmapRequest_<std::allocator<void> > MakePlanCostmapRequest;

typedef boost::shared_ptr< ::upo_rrt_planners::MakePlanCostmapRequest > MakePlanCostmapRequestPtr;
typedef boost::shared_ptr< ::upo_rrt_planners::MakePlanCostmapRequest const> MakePlanCostmapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace upo_rrt_planners

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6161504b92551c2c5f004596a640a89";
  }

  static const char* value(const ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6161504b92551c2ULL;
  static const uint64_t static_value2 = 0xc5f004596a640a89ULL;
};

template<class ContainerAllocator>
struct DataType< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upo_rrt_planners/MakePlanCostmapRequest";
  }

  static const char* value(const ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped goal\n\
nav_msgs/OccupancyGrid costmap\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: nav_msgs/OccupancyGrid\n\
# This represents a 2-D grid map, in which each cell represents the probability of\n\
# occupancy.\n\
\n\
Header header \n\
\n\
#MetaData for the map\n\
MapMetaData info\n\
\n\
# The map data, in row-major order, starting with (0,0).  Occupancy\n\
# probabilities are in the range [0,100].  Unknown is -1.\n\
int8[] data\n\
\n\
================================================================================\n\
MSG: nav_msgs/MapMetaData\n\
# This hold basic information about the characterists of the OccupancyGrid\n\
\n\
# The time at which the map was loaded\n\
time map_load_time\n\
# The map resolution [m/cell]\n\
float32 resolution\n\
# Map width [cells]\n\
uint32 width\n\
# Map height [cells]\n\
uint32 height\n\
# The origin of the map [m, m, rad].  This is the real-world pose of the\n\
# cell (0,0) in the map.\n\
geometry_msgs/Pose origin\n\
";
  }

  static const char* value(const ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
      stream.next(m.costmap);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MakePlanCostmapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upo_rrt_planners::MakePlanCostmapRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "costmap: ";
    s << std::endl;
    Printer< ::nav_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, indent + "  ", v.costmap);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPO_RRT_PLANNERS_MESSAGE_MAKEPLANCOSTMAPREQUEST_H
