// Generated by gencpp from file upo_rrt_planners/MakePlanCostmap.msg
// DO NOT EDIT!


#ifndef UPO_RRT_PLANNERS_MESSAGE_MAKEPLANCOSTMAP_H
#define UPO_RRT_PLANNERS_MESSAGE_MAKEPLANCOSTMAP_H

#include <ros/service_traits.h>


#include <upo_rrt_planners/MakePlanCostmapRequest.h>
#include <upo_rrt_planners/MakePlanCostmapResponse.h>


namespace upo_rrt_planners
{

struct MakePlanCostmap
{

typedef MakePlanCostmapRequest Request;
typedef MakePlanCostmapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MakePlanCostmap
} // namespace upo_rrt_planners


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::upo_rrt_planners::MakePlanCostmap > {
  static const char* value()
  {
    return "4f495652d3b6b0d89b3de5f9e6e2da92";
  }

  static const char* value(const ::upo_rrt_planners::MakePlanCostmap&) { return value(); }
};

template<>
struct DataType< ::upo_rrt_planners::MakePlanCostmap > {
  static const char* value()
  {
    return "upo_rrt_planners/MakePlanCostmap";
  }

  static const char* value(const ::upo_rrt_planners::MakePlanCostmap&) { return value(); }
};


// service_traits::MD5Sum< ::upo_rrt_planners::MakePlanCostmapRequest> should match 
// service_traits::MD5Sum< ::upo_rrt_planners::MakePlanCostmap > 
template<>
struct MD5Sum< ::upo_rrt_planners::MakePlanCostmapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::upo_rrt_planners::MakePlanCostmap >::value();
  }
  static const char* value(const ::upo_rrt_planners::MakePlanCostmapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_rrt_planners::MakePlanCostmapRequest> should match 
// service_traits::DataType< ::upo_rrt_planners::MakePlanCostmap > 
template<>
struct DataType< ::upo_rrt_planners::MakePlanCostmapRequest>
{
  static const char* value()
  {
    return DataType< ::upo_rrt_planners::MakePlanCostmap >::value();
  }
  static const char* value(const ::upo_rrt_planners::MakePlanCostmapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::upo_rrt_planners::MakePlanCostmapResponse> should match 
// service_traits::MD5Sum< ::upo_rrt_planners::MakePlanCostmap > 
template<>
struct MD5Sum< ::upo_rrt_planners::MakePlanCostmapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::upo_rrt_planners::MakePlanCostmap >::value();
  }
  static const char* value(const ::upo_rrt_planners::MakePlanCostmapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::upo_rrt_planners::MakePlanCostmapResponse> should match 
// service_traits::DataType< ::upo_rrt_planners::MakePlanCostmap > 
template<>
struct DataType< ::upo_rrt_planners::MakePlanCostmapResponse>
{
  static const char* value()
  {
    return DataType< ::upo_rrt_planners::MakePlanCostmap >::value();
  }
  static const char* value(const ::upo_rrt_planners::MakePlanCostmapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UPO_RRT_PLANNERS_MESSAGE_MAKEPLANCOSTMAP_H
