//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the upo_rrt_planners package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __upo_rrt_planners__RRTROSWRAPPERCONFIG_H__
#define __upo_rrt_planners__RRTROSWRAPPERCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace upo_rrt_planners
{
  class RRTRosWrapperConfigStatics;

  class RRTRosWrapperConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(RRTRosWrapperConfig &config, const RRTRosWrapperConfig &max, const RRTRosWrapperConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const RRTRosWrapperConfig &config1, const RRTRosWrapperConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, RRTRosWrapperConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const RRTRosWrapperConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RRTRosWrapperConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const RRTRosWrapperConfig &config) const = 0;
      virtual void getValue(const RRTRosWrapperConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T RRTRosWrapperConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (RRTRosWrapperConfig::* field);

      virtual void clamp(RRTRosWrapperConfig &config, const RRTRosWrapperConfig &max, const RRTRosWrapperConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const RRTRosWrapperConfig &config1, const RRTRosWrapperConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, RRTRosWrapperConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const RRTRosWrapperConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, RRTRosWrapperConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const RRTRosWrapperConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const RRTRosWrapperConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, RRTRosWrapperConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, RRTRosWrapperConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<RRTRosWrapperConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(RRTRosWrapperConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("solve_time"==(*_i)->name){solve_time = boost::any_cast<double>(val);}
        if("visualize_rrt_tree"==(*_i)->name){visualize_rrt_tree = boost::any_cast<bool>(val);}
        if("visualize_costmap"==(*_i)->name){visualize_costmap = boost::any_cast<bool>(val);}
        if("show_statistics"==(*_i)->name){show_statistics = boost::any_cast<bool>(val);}
        if("path_smoothing"==(*_i)->name){path_smoothing = boost::any_cast<bool>(val);}
        if("smoothing_samples"==(*_i)->name){smoothing_samples = boost::any_cast<int>(val);}
        if("goal_bias"==(*_i)->name){goal_bias = boost::any_cast<double>(val);}
        if("max_rrt_insertion_dist"==(*_i)->name){max_rrt_insertion_dist = boost::any_cast<double>(val);}
        if("rrtstar_first_path_biasing"==(*_i)->name){rrtstar_first_path_biasing = boost::any_cast<bool>(val);}
        if("rrtstar_first_path_bias"==(*_i)->name){rrtstar_first_path_bias = boost::any_cast<double>(val);}
        if("rrtstar_first_path_stddev"==(*_i)->name){rrtstar_first_path_stddev = boost::any_cast<double>(val);}
        if("full_path_biasing"==(*_i)->name){full_path_biasing = boost::any_cast<bool>(val);}
        if("full_path_bias"==(*_i)->name){full_path_bias = boost::any_cast<double>(val);}
        if("full_path_stddev"==(*_i)->name){full_path_stddev = boost::any_cast<double>(val);}
        if("gmm_biasing"==(*_i)->name){gmm_biasing = boost::any_cast<bool>(val);}
        if("gmm_bias"==(*_i)->name){gmm_bias = boost::any_cast<double>(val);}
      }
    }

    double solve_time;
bool visualize_rrt_tree;
bool visualize_costmap;
bool show_statistics;
bool path_smoothing;
int smoothing_samples;
double goal_bias;
double max_rrt_insertion_dist;
bool rrtstar_first_path_biasing;
double rrtstar_first_path_bias;
double rrtstar_first_path_stddev;
bool full_path_biasing;
double full_path_bias;
double full_path_stddev;
bool gmm_biasing;
double gmm_bias;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double solve_time;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool visualize_rrt_tree;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool visualize_costmap;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool show_statistics;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool path_smoothing;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int smoothing_samples;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double goal_bias;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_rrt_insertion_dist;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool rrtstar_first_path_biasing;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rrtstar_first_path_bias;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double rrtstar_first_path_stddev;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool full_path_biasing;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double full_path_bias;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double full_path_stddev;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool gmm_biasing;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double gmm_bias;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("RRTRosWrapperConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const RRTRosWrapperConfig &__max__ = __getMax__();
      const RRTRosWrapperConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const RRTRosWrapperConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const RRTRosWrapperConfig &__getDefault__();
    static const RRTRosWrapperConfig &__getMax__();
    static const RRTRosWrapperConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const RRTRosWrapperConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void RRTRosWrapperConfig::ParamDescription<std::string>::clamp(RRTRosWrapperConfig &config, const RRTRosWrapperConfig &max, const RRTRosWrapperConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class RRTRosWrapperConfigStatics
  {
    friend class RRTRosWrapperConfig;

    RRTRosWrapperConfigStatics()
    {
RRTRosWrapperConfig::GroupDescription<RRTRosWrapperConfig::DEFAULT, RRTRosWrapperConfig> Default("Default", "", 0, 0, true, &RRTRosWrapperConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.solve_time = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.solve_time = 9.9;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.solve_time = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("solve_time", "double", 0, "time that the RRT is allowed to plan a path", "", &RRTRosWrapperConfig::solve_time)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("solve_time", "double", 0, "time that the RRT is allowed to plan a path", "", &RRTRosWrapperConfig::solve_time)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.visualize_rrt_tree = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.visualize_rrt_tree = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.visualize_rrt_tree = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("visualize_rrt_tree", "bool", 0, "Whether or not to publish the rrt tree for visualization purposes", "", &RRTRosWrapperConfig::visualize_rrt_tree)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("visualize_rrt_tree", "bool", 0, "Whether or not to publish the rrt tree for visualization purposes", "", &RRTRosWrapperConfig::visualize_rrt_tree)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.visualize_costmap = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.visualize_costmap = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.visualize_costmap = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("visualize_costmap", "bool", 0, "Whether or not to publish the costmap for visualization purposes", "", &RRTRosWrapperConfig::visualize_costmap)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("visualize_costmap", "bool", 0, "Whether or not to publish the costmap for visualization purposes", "", &RRTRosWrapperConfig::visualize_costmap)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.show_statistics = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.show_statistics = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.show_statistics = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("show_statistics", "bool", 0, "Whether or not to print on the screen the RRT statistics", "", &RRTRosWrapperConfig::show_statistics)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("show_statistics", "bool", 0, "Whether or not to print on the screen the RRT statistics", "", &RRTRosWrapperConfig::show_statistics)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.path_smoothing = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.path_smoothing = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.path_smoothing = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("path_smoothing", "bool", 0, "Whether or not to do a simple smoothing of the RRT path", "", &RRTRosWrapperConfig::path_smoothing)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("path_smoothing", "bool", 0, "Whether or not to do a simple smoothing of the RRT path", "", &RRTRosWrapperConfig::path_smoothing)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.smoothing_samples = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.smoothing_samples = 100;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.smoothing_samples = 5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<int>("smoothing_samples", "int", 0, "If 'path_smoothing is enabled', it indicates the number of samples to include in the window for smoothing", "", &RRTRosWrapperConfig::smoothing_samples)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<int>("smoothing_samples", "int", 0, "If 'path_smoothing is enabled', it indicates the number of samples to include in the window for smoothing", "", &RRTRosWrapperConfig::smoothing_samples)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.goal_bias = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.goal_bias = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.goal_bias = 0.05;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("goal_bias", "double", 0, "Percentage of goal biasing", "", &RRTRosWrapperConfig::goal_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("goal_bias", "double", 0, "Percentage of goal biasing", "", &RRTRosWrapperConfig::goal_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_rrt_insertion_dist = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_rrt_insertion_dist = 5.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_rrt_insertion_dist = 0.25;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("max_rrt_insertion_dist", "double", 0, "Max distance (meters) to insert a new node", "", &RRTRosWrapperConfig::max_rrt_insertion_dist)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("max_rrt_insertion_dist", "double", 0, "Max distance (meters) to insert a new node", "", &RRTRosWrapperConfig::max_rrt_insertion_dist)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rrtstar_first_path_biasing = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rrtstar_first_path_biasing = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rrtstar_first_path_biasing = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("rrtstar_first_path_biasing", "bool", 0, "Whether or not to bias the sampling from the first solution found", "", &RRTRosWrapperConfig::rrtstar_first_path_biasing)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("rrtstar_first_path_biasing", "bool", 0, "Whether or not to bias the sampling from the first solution found", "", &RRTRosWrapperConfig::rrtstar_first_path_biasing)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rrtstar_first_path_bias = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rrtstar_first_path_bias = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rrtstar_first_path_bias = 0.8;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("rrtstar_first_path_bias", "double", 0, "Percentage of sampling from the first solution found", "", &RRTRosWrapperConfig::rrtstar_first_path_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("rrtstar_first_path_bias", "double", 0, "Percentage of sampling from the first solution found", "", &RRTRosWrapperConfig::rrtstar_first_path_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rrtstar_first_path_stddev = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rrtstar_first_path_stddev = 4.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rrtstar_first_path_stddev = 0.4;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("rrtstar_first_path_stddev", "double", 0, "Standard deviation (m) around the first solution found to sample from", "", &RRTRosWrapperConfig::rrtstar_first_path_stddev)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("rrtstar_first_path_stddev", "double", 0, "Standard deviation (m) around the first solution found to sample from", "", &RRTRosWrapperConfig::rrtstar_first_path_stddev)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.full_path_biasing = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.full_path_biasing = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.full_path_biasing = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("full_path_biasing", "bool", 0, "Whether or not to bias the sampling from a plath passed", "", &RRTRosWrapperConfig::full_path_biasing)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("full_path_biasing", "bool", 0, "Whether or not to bias the sampling from a plath passed", "", &RRTRosWrapperConfig::full_path_biasing)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.full_path_bias = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.full_path_bias = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.full_path_bias = 0.8;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("full_path_bias", "double", 0, "Percentage of sampling from the path passed", "", &RRTRosWrapperConfig::full_path_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("full_path_bias", "double", 0, "Percentage of sampling from the path passed", "", &RRTRosWrapperConfig::full_path_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.full_path_stddev = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.full_path_stddev = 4.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.full_path_stddev = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("full_path_stddev", "double", 0, "Standard deviation (m) around the path passed to sample from", "", &RRTRosWrapperConfig::full_path_stddev)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("full_path_stddev", "double", 0, "Standard deviation (m) around the path passed to sample from", "", &RRTRosWrapperConfig::full_path_stddev)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gmm_biasing = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gmm_biasing = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gmm_biasing = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("gmm_biasing", "bool", 0, "Whether or not to bias the sampling from a GMM", "", &RRTRosWrapperConfig::gmm_biasing)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<bool>("gmm_biasing", "bool", 0, "Whether or not to bias the sampling from a GMM", "", &RRTRosWrapperConfig::gmm_biasing)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gmm_bias = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gmm_bias = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gmm_bias = 0.95;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("gmm_bias", "double", 0, "Percentage of sampling from the GMM", "", &RRTRosWrapperConfig::gmm_bias)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(RRTRosWrapperConfig::AbstractParamDescriptionConstPtr(new RRTRosWrapperConfig::ParamDescription<double>("gmm_bias", "double", 0, "Percentage of sampling from the GMM", "", &RRTRosWrapperConfig::gmm_bias)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(RRTRosWrapperConfig::AbstractGroupDescriptionConstPtr(new RRTRosWrapperConfig::GroupDescription<RRTRosWrapperConfig::DEFAULT, RRTRosWrapperConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<RRTRosWrapperConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<RRTRosWrapperConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<RRTRosWrapperConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    RRTRosWrapperConfig __max__;
    RRTRosWrapperConfig __min__;
    RRTRosWrapperConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const RRTRosWrapperConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static RRTRosWrapperConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &RRTRosWrapperConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const RRTRosWrapperConfig &RRTRosWrapperConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const RRTRosWrapperConfig &RRTRosWrapperConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const RRTRosWrapperConfig &RRTRosWrapperConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<RRTRosWrapperConfig::AbstractParamDescriptionConstPtr> &RRTRosWrapperConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<RRTRosWrapperConfig::AbstractGroupDescriptionConstPtr> &RRTRosWrapperConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const RRTRosWrapperConfigStatics *RRTRosWrapperConfig::__get_statics__()
  {
    const static RRTRosWrapperConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = RRTRosWrapperConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __RRTROSWRAPPERRECONFIGURATOR_H__
