// Generated by gencpp from file upo_msgs/PersonPoseUPO.msg
// DO NOT EDIT!


#ifndef UPO_MSGS_MESSAGE_PERSONPOSEUPO_H
#define UPO_MSGS_MESSAGE_PERSONPOSEUPO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Quaternion.h>

namespace upo_msgs
{
template <class ContainerAllocator>
struct PersonPoseUPO_
{
  typedef PersonPoseUPO_<ContainerAllocator> Type;

  PersonPoseUPO_()
    : header()
    , id(0)
    , vel(0.0)
    , position()
    , orientation()  {
    }
  PersonPoseUPO_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , vel(0.0)
    , position(_alloc)
    , orientation(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _id_type;
  _id_type id;

   typedef double _vel_type;
  _vel_type vel;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> const> ConstPtr;

}; // struct PersonPoseUPO_

typedef ::upo_msgs::PersonPoseUPO_<std::allocator<void> > PersonPoseUPO;

typedef boost::shared_ptr< ::upo_msgs::PersonPoseUPO > PersonPoseUPOPtr;
typedef boost::shared_ptr< ::upo_msgs::PersonPoseUPO const> PersonPoseUPOConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upo_msgs::PersonPoseUPO_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace upo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'upo_msgs': ['/home/im_hongxian_yi/catkin_ws/src/upo_robot_navigation/upo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e33e12367f5d203eb13369fe8af6884a";
  }

  static const char* value(const ::upo_msgs::PersonPoseUPO_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe33e12367f5d203eULL;
  static const uint64_t static_value2 = 0xb13369fe8af6884aULL;
};

template<class ContainerAllocator>
struct DataType< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upo_msgs/PersonPoseUPO";
  }

  static const char* value(const ::upo_msgs::PersonPoseUPO_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 id\n\
float64 vel\n\
geometry_msgs/Point position \n\
geometry_msgs/Quaternion orientation \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::upo_msgs::PersonPoseUPO_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.vel);
      stream.next(m.position);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonPoseUPO_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upo_msgs::PersonPoseUPO_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "vel: ";
    Printer<double>::stream(s, indent + "  ", v.vel);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPO_MSGS_MESSAGE_PERSONPOSEUPO_H
