// Generated by gencpp from file upo_msgs/PersonPoseArrayUPO.msg
// DO NOT EDIT!


#ifndef UPO_MSGS_MESSAGE_PERSONPOSEARRAYUPO_H
#define UPO_MSGS_MESSAGE_PERSONPOSEARRAYUPO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <upo_msgs/PersonPoseUPO.h>

namespace upo_msgs
{
template <class ContainerAllocator>
struct PersonPoseArrayUPO_
{
  typedef PersonPoseArrayUPO_<ContainerAllocator> Type;

  PersonPoseArrayUPO_()
    : header()
    , size(0)
    , personPoses()  {
    }
  PersonPoseArrayUPO_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , size(0)
    , personPoses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _size_type;
  _size_type size;

   typedef std::vector< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >::other >  _personPoses_type;
  _personPoses_type personPoses;





  typedef boost::shared_ptr< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> const> ConstPtr;

}; // struct PersonPoseArrayUPO_

typedef ::upo_msgs::PersonPoseArrayUPO_<std::allocator<void> > PersonPoseArrayUPO;

typedef boost::shared_ptr< ::upo_msgs::PersonPoseArrayUPO > PersonPoseArrayUPOPtr;
typedef boost::shared_ptr< ::upo_msgs::PersonPoseArrayUPO const> PersonPoseArrayUPOConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace upo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'upo_msgs': ['/home/im_hongxian_yi/catkin_ws/src/upo_robot_navigation/upo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b639a8fec51263bcdabcb919ea55b99e";
  }

  static const char* value(const ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb639a8fec51263bcULL;
  static const uint64_t static_value2 = 0xdabcb919ea55b99eULL;
};

template<class ContainerAllocator>
struct DataType< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upo_msgs/PersonPoseArrayUPO";
  }

  static const char* value(const ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 size\n\
PersonPoseUPO[] personPoses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: upo_msgs/PersonPoseUPO\n\
Header header\n\
uint32 id\n\
float64 vel\n\
geometry_msgs/Point position \n\
geometry_msgs/Quaternion orientation \n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.size);
      stream.next(m.personPoses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonPoseArrayUPO_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upo_msgs::PersonPoseArrayUPO_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "size: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.size);
    s << indent << "personPoses[]" << std::endl;
    for (size_t i = 0; i < v.personPoses.size(); ++i)
    {
      s << indent << "  personPoses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::upo_msgs::PersonPoseUPO_<ContainerAllocator> >::stream(s, indent + "    ", v.personPoses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPO_MSGS_MESSAGE_PERSONPOSEARRAYUPO_H
