(cl:defpackage gmm_sampling-srv
  (:use )
  (:export
   "GETAPPROACHGMMPROB"
   "<GETAPPROACHGMMPROB-REQUEST>"
   "GETAPPROACHGMMPROB-REQUEST"
   "<GETAPPROACHGMMPROB-RESPONSE>"
   "GETAPPROACHGMMPROB-RESPONSE"
   "GETAPPROACHGMMPROBS"
   "<GETAPPROACHGMMPROBS-REQUEST>"
   "GETAPPROACHGMMPROBS-REQUEST"
   "<GETAPPROACHGMMPROBS-RESPONSE>"
   "GETAPPROACHGMMPROBS-RESPONSE"
   "GETAPPROACHGMMSAMPLES"
   "<GETAPPROACHGMMSAMPLES-REQUEST>"
   "GETAPPROACHGMMSAMPLES-REQUEST"
   "<GETAPPROACHGMMSAMPLES-RESPONSE>"
   "GETAPPROACHGMMSAMPLES-RESPONSE"
  ))

