(cl:defpackage upo_msgs-msg
  (:use )
  (:export
   "<PERSONGOALARRAYUPO>"
   "PERSONGOALARRAYUPO"
   "<PERSONGOALUPO>"
   "PERSONGOALUPO"
   "<PERSONPOSEARRAYUPO>"
   "PERSONPOSEARRAYUPO"
   "<PERSONPOSEUPO>"
   "PERSONPOSEUPO"
  ))

